//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try font.validate()
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 4 colors.
  struct color {
    /// Color `background-white`.
    static let backgroundWhite = Rswift.ColorResource(bundle: R.hostingBundle, name: "background-white")
    /// Color `box-white`.
    static let boxWhite = Rswift.ColorResource(bundle: R.hostingBundle, name: "box-white")
    /// Color `hospital-blue`.
    static let hospitalBlue = Rswift.ColorResource(bundle: R.hostingBundle, name: "hospital-blue")
    /// Color `slate-black`.
    static let slateBlack = Rswift.ColorResource(bundle: R.hostingBundle, name: "slate-black")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "background-white", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func backgroundWhite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.backgroundWhite, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "box-white", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func boxWhite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.boxWhite, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "hospital-blue", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func hospitalBlue(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.hospitalBlue, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "slate-black", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func slateBlack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.slateBlack, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 9 files.
  struct file {
    /// Resource file `AVENGEANCE HEROIC AVENGER AT.ttf`.
    static let avengeanceheroicavengeratTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "AVENGEANCE HEROIC AVENGER AT", pathExtension: "ttf")
    /// Resource file `AVENGEANCE HEROIC AVENGER BD.ttf`.
    static let avengeanceheroicavengerbdTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "AVENGEANCE HEROIC AVENGER BD", pathExtension: "ttf")
    /// Resource file `AVENGEANCE HEROIC AVENGER BI.ttf`.
    static let avengeanceheroicavengerbiTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "AVENGEANCE HEROIC AVENGER BI", pathExtension: "ttf")
    /// Resource file `AVENGEANCE HEROIC AVENGER.ttf`.
    static let avengeanceheroicavengerTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "AVENGEANCE HEROIC AVENGER", pathExtension: "ttf")
    /// Resource file `Lato-Black.ttf`.
    static let latoBlackTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Lato-Black", pathExtension: "ttf")
    /// Resource file `Lato-Bold.ttf`.
    static let latoBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Lato-Bold", pathExtension: "ttf")
    /// Resource file `Lato-BoldItalic.ttf`.
    static let latoBoldItalicTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Lato-BoldItalic", pathExtension: "ttf")
    /// Resource file `Lato-Italic.ttf`.
    static let latoItalicTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Lato-Italic", pathExtension: "ttf")
    /// Resource file `Lato-Regular.ttf`.
    static let latoRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Lato-Regular", pathExtension: "ttf")

    /// `bundle.url(forResource: "AVENGEANCE HEROIC AVENGER AT", withExtension: "ttf")`
    static func avengeanceheroicavengeratTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avengeanceheroicavengeratTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "AVENGEANCE HEROIC AVENGER BD", withExtension: "ttf")`
    static func avengeanceheroicavengerbdTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avengeanceheroicavengerbdTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "AVENGEANCE HEROIC AVENGER BI", withExtension: "ttf")`
    static func avengeanceheroicavengerbiTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avengeanceheroicavengerbiTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "AVENGEANCE HEROIC AVENGER", withExtension: "ttf")`
    static func avengeanceheroicavengerTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avengeanceheroicavengerTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Lato-Black", withExtension: "ttf")`
    static func latoBlackTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.latoBlackTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Lato-Bold", withExtension: "ttf")`
    static func latoBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.latoBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Lato-BoldItalic", withExtension: "ttf")`
    static func latoBoldItalicTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.latoBoldItalicTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Lato-Italic", withExtension: "ttf")`
    static func latoItalicTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.latoItalicTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Lato-Regular", withExtension: "ttf")`
    static func latoRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.latoRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.font` struct is generated, and contains static references to 9 fonts.
  struct font: Rswift.Validatable {
    /// Font `AvengeanceHeroicAvengerBoldItalic`.
    static let avengeanceHeroicAvengerBoldItalic = Rswift.FontResource(fontName: "AvengeanceHeroicAvengerBoldItalic")
    /// Font `AvengeanceHeroicAvengerBold`.
    static let avengeanceHeroicAvengerBold = Rswift.FontResource(fontName: "AvengeanceHeroicAvengerBold")
    /// Font `AvengeanceHeroicAvengerItalic`.
    static let avengeanceHeroicAvengerItalic = Rswift.FontResource(fontName: "AvengeanceHeroicAvengerItalic")
    /// Font `AvengeanceHeroicAvengerNormal`.
    static let avengeanceHeroicAvengerNormal = Rswift.FontResource(fontName: "AvengeanceHeroicAvengerNormal")
    /// Font `Lato-Black`.
    static let latoBlack = Rswift.FontResource(fontName: "Lato-Black")
    /// Font `Lato-BoldItalic`.
    static let latoBoldItalic = Rswift.FontResource(fontName: "Lato-BoldItalic")
    /// Font `Lato-Bold`.
    static let latoBold = Rswift.FontResource(fontName: "Lato-Bold")
    /// Font `Lato-Italic`.
    static let latoItalic = Rswift.FontResource(fontName: "Lato-Italic")
    /// Font `Lato-Regular`.
    static let latoRegular = Rswift.FontResource(fontName: "Lato-Regular")

    /// `UIFont(name: "AvengeanceHeroicAvengerBold", size: ...)`
    static func avengeanceHeroicAvengerBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avengeanceHeroicAvengerBold, size: size)
    }

    /// `UIFont(name: "AvengeanceHeroicAvengerBoldItalic", size: ...)`
    static func avengeanceHeroicAvengerBoldItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avengeanceHeroicAvengerBoldItalic, size: size)
    }

    /// `UIFont(name: "AvengeanceHeroicAvengerItalic", size: ...)`
    static func avengeanceHeroicAvengerItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avengeanceHeroicAvengerItalic, size: size)
    }

    /// `UIFont(name: "AvengeanceHeroicAvengerNormal", size: ...)`
    static func avengeanceHeroicAvengerNormal(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avengeanceHeroicAvengerNormal, size: size)
    }

    /// `UIFont(name: "Lato-Black", size: ...)`
    static func latoBlack(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: latoBlack, size: size)
    }

    /// `UIFont(name: "Lato-Bold", size: ...)`
    static func latoBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: latoBold, size: size)
    }

    /// `UIFont(name: "Lato-BoldItalic", size: ...)`
    static func latoBoldItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: latoBoldItalic, size: size)
    }

    /// `UIFont(name: "Lato-Italic", size: ...)`
    static func latoItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: latoItalic, size: size)
    }

    /// `UIFont(name: "Lato-Regular", size: ...)`
    static func latoRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: latoRegular, size: size)
    }

    static func validate() throws {
      if R.font.avengeanceHeroicAvengerBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvengeanceHeroicAvengerBold' could not be loaded, is 'AVENGEANCE HEROIC AVENGER BD.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avengeanceHeroicAvengerBoldItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvengeanceHeroicAvengerBoldItalic' could not be loaded, is 'AVENGEANCE HEROIC AVENGER BI.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avengeanceHeroicAvengerItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvengeanceHeroicAvengerItalic' could not be loaded, is 'AVENGEANCE HEROIC AVENGER AT.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avengeanceHeroicAvengerNormal(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvengeanceHeroicAvengerNormal' could not be loaded, is 'AVENGEANCE HEROIC AVENGER.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.latoBlack(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Lato-Black' could not be loaded, is 'Lato-Black.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.latoBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Lato-Bold' could not be loaded, is 'Lato-Bold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.latoBoldItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Lato-BoldItalic' could not be loaded, is 'Lato-BoldItalic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.latoItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Lato-Italic' could not be loaded, is 'Lato-Italic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.latoRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Lato-Regular' could not be loaded, is 'Lato-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 4 images.
  struct image {
    /// Image `chart-icon`.
    static let chartIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "chart-icon")
    /// Image `news-icon`.
    static let newsIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "news-icon")
    /// Image `settings-icon`.
    static let settingsIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "settings-icon")
    /// Image `stats-icon`.
    static let statsIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "stats-icon")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "chart-icon", bundle: ..., traitCollection: ...)`
    static func chartIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chartIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "news-icon", bundle: ..., traitCollection: ...)`
    static func newsIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.newsIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "settings-icon", bundle: ..., traitCollection: ...)`
    static func settingsIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.settingsIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "stats-icon", bundle: ..., traitCollection: ...)`
    static func statsIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.statsIcon, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = StatsViewController

      let bundle = R.hostingBundle
      let name = "Main"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
